-   id: oxipng
    name: oxipng
    entry: oxipng
    language: rust
    'types': [png]
    args: []
    require_serial: true
    additional_dependencies: ["cli:oxipng:5.0.1"]
    minimum_pre_commit_version: '0'
    description: 'Multithreaded PNG optimizer written in Rust.'
