-   id: oxipng
    name: oxipng
    entry: oxipng
    language: rust
    'types': [png]
    args: []
    require_serial: true
    additional_dependencies: ["cli:oxipng:4.0.2"]
    minimum_pre_commit_version: '0'
